---
- include: validate.yml
  delegate_to: localhost
  when:
  tags:
    - always

- include: create-vm.yml
  delegate_to: localhost
  tags:
    - provision

- include: snapshot.yml
  when:
    - proxmox_task.msg.find("already exists") == -1
  delegate_to: localhost
  tags:
    - provision

- include: delete-vm.yml
  delegate_to: localhost
  tags:
    - never
    - delete
