---
- hosts: all
  gather_facts: false
  tasks:
    - name: "Create cloud-init-template"
      include_role:
        name: proxmox_vms
        tasks_from: cloud-init-config.yml

    - name: "Create the first vm"
      ansible.builtin.include_role:
        name: proxmox_vms
